### ISSUE TITLE
Vendor code not in remote repository

### ISSUE THREAD

**Issue by torfuzx** [nlamirault/abraracourcix#7]
it is possible to push golang dependencies code into remote repository (like [1]).
My remote repository doesn't contains code [2], but beats project seems to push dependencies code [3].
How to do this ?

[1] : https://github.com/elastic/beats
[2] : https://github.com/nlamirault/abraracourcix/tree/master/vendor/github.com/garyburd
[3] : https://github.com/elastic/beats/tree/master/vendor/github.com/garyburd/redigo

Hi:
I find your issue for glide.I don't know how to do.
Can you tell me the way to solve it?

**Comment by nlamirault** [comment]
I use a recent version of glide, and i'm using 3 options to vendoring code : 

```bash
$ glide -v
glide version 0.10.0
$ glide up -u -s -v
```

**Comment by torfuzx** [comment]
Thank you very very very much.
